version: '3.3'

services:
  redis:
    container_name: unn-schedule-redis
    image: redis
    restart: always
    ports:
    - "6379:6379"

  bot:
    image: unn-schedule-bot
    container_name: unn-schedule-bot
    build: ./
    env_file: ./.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    depends_on:
      - redis
